default: &default
  adapter: postgresql
  encoding: unicode
  username: vagrant
  pool: 5

development:
  <<: *default
  database: obtvse_development

test:
  <<: *default
  database: obtvse_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DATABASE_POOL'] || 5 %>
