<% def env(a, b); e = ENV["obtvse_#{a}"]; e ? e : b; end %>

title: <%= env :title,     'Blog Title' %>
domain: <%= env :domain,   'http://www.example.com' %>
name:    <%= env :name,    'Full Name' %>
twitter: <%= env :twitter, 'handle' %>
github:  <%= env :github,  'username'  %>
email:   <%= env :email,   'email@example.com'  %>
about:   <%= env :about,   'Example Tagline That is Longer.' %>
aud:     <%= env :aud,     "l0DD4NSL5GjnTdVsk6CtL2M0diB2aq3E" %>
iss:     <%= env :iss,     "https://ib-blog.auth0.com/" %>
cert: |
  -----BEGIN CERTIFICATE-----
  MIIC/TCCAeWgAwIBAgIJcubT+chCu4iyMA0GCSqGSIb3DQEBCwUAMBwxGjAYBgNV
  BAMTEWliLWJsb2cuYXV0aDAuY29tMB4XDTE4MDUxNDAwMDU0M1oXDTMyMDEyMTAw
  MDU0M1owHDEaMBgGA1UEAxMRaWItYmxvZy5hdXRoMC5jb20wggEiMA0GCSqGSIb3
  DQEBAQUAA4IBDwAwggEKAoIBAQC8PyT1dTwyY3RgUGVTPcVSkCkYVaE037Vb3SlZ
  k0mafCc5VwtGfOyucWCjBvc44yT6QTOTP55UxdVf0PSyt4xTe5a9MDDMZh+QYUUu
  Zw2fw/i8NJAGgzWjuJMZsV5Djq44lzFmIQyqZ8etZx25dTiwycM67BNdVbekSQ3Y
  AoBylJvKnHqFOgXLuWrSRMDgLhTxNI7Glpl8NqRgydcN4lnVsD06KcAx1OSqtH4B
  Hlzp/qCD0DdYaI8AN+d+dAQzw0bSRCVFJjd/wdjL09AaygEN6PT3OPn9o+AM01y6
  9PgDTiPCHd8XEaraRNpXdPpKhLSj2ieJPmNjBmhLMj8Dq1pVAgMBAAGjQjBAMA8G
  A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBGKu4wkFX0uUlcRl8iNRmOy/5zqMA4G
  A1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEASO9yOoKJdSRhNFuOOhMc
  P2rjzYUyUledXQo7g/UljigMuwG5+EZL4qIcEpFh7JrA12Agok+fVZk84LC8iUP2
  P3OJtjAxINXVa6u2EdpC5zJ6mtU4NmNrb8jP5E7r7E+XR0XIBuZV3xNxqAkfcD4/
  Qig8QEvUF9UBL+LqJiUQrooHqw4UzBztM9h1AdIjO1AAg79CgKZu/md3MXdDbV4j
  WUSi+YyYDijyp8x/vN6d3UjXv0O+q5RaPYd1EvUQ4Gx26M9+1yvKphDF12rypzsA
  s5v+xj5qSSqPdAOHIV9rnPtydlg41eNGdY1dQNhDWv6pjBdfNwxXqmSnhu1YLKF7
  4g==
  -----END CERTIFICATE-----


# Google Analytics
ga_id:   <%= env :ga,      ''  %>
